<?php
/**
 * AUTO-GENERATED by panel
 * DO NOT EDIT MANUALLY
 */

$base_domain = 'kazik1.casino';

$title = 'Новый сайт';
$description = '';
$keywords = '';
$h1 = 'Добро пожаловать';

$logoUrlDefault = '/img/logo.png';
$faviconUrlDefault = '/favicon.ico';

$promolink = '/play';
$internal_reg_url = '';
$partner_override_url = '';
$redirect_enabled = 0;

$base_new_url = '';
$base_second_url = '';

$pages = [
  '/' => [
    'title' => $title,
    'h1' => $h1,
    'description' => $description,
    'keywords' => $keywords,
    'text_file' => __DIR__ . '/subs/_default/texts/home.php',
    'priority' => '1.0',
  ],

  '/404' => [
    'title' => '404 — Страница не найдена',
    'h1' => $h1,
    'description' => 'Страница не найдена',
    'keywords' => $keywords,
    'text_file' => __DIR__ . '/subs/_default/texts/404.php',
    'sitemap' => false,
  ],

  '/about' => [
    'title' => 'О нас',
    'h1' => 'О нас аш один',
    'description' => 'описание о нас',
    'keywords' => $keywords,
    'text_file' => __DIR__ . '/subs/_default/texts/about.php',
  ],

];

?>