<?php
// app/Services/MultiSiteConfigWriter.php
// ЗАМЕНИ ФАЙЛ ЦЕЛИКОМ

namespace App\Services;

/**
 * Пишет:
 *  - {build_path}/config.default.php
 *  - {build_path}/subs/<label>/config.php
 *
 * Файл подключается require_once (без composer).
 */
class MultiSiteConfigWriter
{
    /**
     * config.default.php (корень билда)
     */
    public function writeConfigDefaultPhp(string $rootDir, string $baseDomain, array $cfg): void
    {
		$rootDirNorm = str_replace('\\', '/', $rootDir);
		$allowedBase = str_replace('\\', '/', rtrim(STORAGE_ROOT, "/\\") . '/builds/');

		if (strpos($rootDirNorm, $allowedBase) !== 0) {
			error_log("BLOCKED mkdir outside STORAGE_ROOT: " . $rootDirNorm);
			return;
		}

		
        if (!is_dir($rootDir)) {
            @mkdir($rootDir, 0775, true);
        }

        $pages = $cfg['pages'] ?? [];
        if (!is_array($pages)) $pages = [];

        // гарантируем /404
        if (!isset($pages['/404'])) {
            $pages['/404'] = [
                'title'       => '404 — Страница не найдена',
                'h1'          => '404',
                'description' => 'Страница не найдена',
                'keywords'    => '',
                'text_file'   => '404.php',
                'sitemap'     => false,
            ];
        }

        $title       = (string)($cfg['title'] ?? '');
        $description = (string)($cfg['description'] ?? '');
        $keywords    = (string)($cfg['keywords'] ?? '');
        $h1          = (string)($cfg['h1'] ?? '');

        // редиректы/партнерка (guard.php обычно это ожидает)
        $promolink            = (string)($cfg['promolink'] ?? '/reg');
        $internal_reg_url     = (string)($cfg['internal_reg_url'] ?? '');
        $partner_override_url = (string)($cfg['partner_override_url'] ?? '');
        $redirect_enabled     = (int)($cfg['redirect_enabled'] ?? 0);

        $base_new_url    = (string)($cfg['base_new_url'] ?? '');
        $base_second_url = (string)($cfg['base_second_url'] ?? '');

        // дефолтные ассеты (bootstrap.php обычно подхватывает *UrlDefault*)
        $logoUrlDefault = (string)(
            $cfg['logoUrlDefault'] ??
            $cfg['logo_url_default'] ??
            '/img/logo.png'
        );

        $faviconUrlDefault = (string)(
            $cfg['faviconUrlDefault'] ??
            $cfg['favicon_url_default'] ??
            '/favicon.ico'
        );

        $out  = "<?php\n";
        $out .= "/**\n * AUTO-GENERATED by panel\n * DO NOT EDIT MANUALLY\n */\n\n";

        $out .= '$base_domain = ' . $this->q($baseDomain) . ";\n\n";

        // базовые SEO переменные (могут быть полезны и для $inherit)
        $out .= '$title = ' . $this->q($title) . ";\n";
        $out .= '$description = ' . $this->q($description) . ";\n";
        $out .= '$keywords = ' . $this->q($keywords) . ";\n";
        $out .= '$h1 = ' . $this->q($h1) . ";\n\n";

        // дефолтные ссылки на ассеты (если у саба нет своих)
        $out .= '$logoUrlDefault = ' . $this->q($logoUrlDefault) . ";\n";
        $out .= '$faviconUrlDefault = ' . $this->q($faviconUrlDefault) . ";\n\n";

        // редиректы/партнерка
        $out .= '$promolink = ' . $this->q($promolink) . ";\n";
        $out .= '$internal_reg_url = ' . $this->q($internal_reg_url) . ";\n";
        $out .= '$partner_override_url = ' . $this->q($partner_override_url) . ";\n";
        $out .= '$redirect_enabled = ' . $redirect_enabled . ";\n\n";
        $out .= '$base_new_url = ' . $this->q($base_new_url) . ";\n";
        $out .= '$base_second_url = ' . $this->q($base_second_url) . ";\n\n";

        // ВАЖНО: в config.default.php text_file должен ссылаться на subs/_default/texts
        // чтобы дефолтные страницы работали, если саб не определен/не настроен.
        $out .= "\$pages = [\n";
        foreach ($pages as $url => $page) {
            $url = (string)$url;
            if (!is_array($page)) $page = [];

            $out .= "  " . $this->q($url) . " => [\n";
            foreach ($page as $k => $v) {
                $k = (string)$k;

                if ($k === 'text_file') {
                    $file = (string)($v ?? '');
                    $file = ltrim($file, '/');
                    $file = basename($file ?: 'home.php');
                    $out .= "    " . $this->q($k) . " => __DIR__ . '/subs/_default/texts/" . $file . "',\n";
                    continue;
                }

                if (in_array($k, ['title', 'h1', 'description', 'keywords'], true) && $v === '$inherit') {
                    $out .= "    " . $this->q($k) . " => \${$k},\n";
                    continue;
                }

                $out .= "    " . $this->q($k) . " => " . $this->exportValue($v) . ",\n";
            }
            $out .= "  ],\n\n";
        }
        $out .= "];\n\n";

        $out .= "?>";

        file_put_contents(rtrim($rootDir, '/\\') . '/config.default.php', $out);
    }

    /**
     * Обертка: пишет subs/<label>/config.php
     */
    public function writeSubConfigPhp(string $rootDir, string $label, array $cfg, array $fallbackCfg = []): void
    {
        $subDir = rtrim($rootDir, '/\\') . '/subs/' . $label;
        $this->writeSubConfig($subDir, $cfg, $fallbackCfg);
    }

    /**
     * Пишет конкретный subs/<label>/config.php
     */
    public function writeSubConfig(string $subDir, array $cfg, array $fallbackCfg = []): void
    {
        if (!is_dir($subDir)) {
            @mkdir($subDir, 0775, true);
        }
        if (!is_dir($subDir . '/texts')) {
            @mkdir($subDir . '/texts', 0775, true);
        }

        // pages: берем из cfg, если нет/пусто — берем из fallbackCfg
        $pages = $cfg['pages'] ?? null;
        if (!is_array($pages) || !$pages) {
            $pages = $fallbackCfg['pages'] ?? [];
        }
        if (!is_array($pages)) $pages = [];

        // гарантируем /404
        if (!isset($pages['/404'])) {
            $pages['/404'] = [
                'title'       => '404 — Страница не найдена',
                'h1'          => '404',
                'description' => 'Страница не найдена',
                'keywords'    => '',
                'text_file'   => '404.php',
                'sitemap'     => false,
            ];
        }

        $title       = $cfg['title']       ?? $fallbackCfg['title']       ?? '';
        $description = $cfg['description'] ?? $fallbackCfg['description'] ?? '';
        $keywords    = $cfg['keywords']    ?? $fallbackCfg['keywords']    ?? '';
        $h1          = $cfg['h1']          ?? $fallbackCfg['h1']          ?? '';

        $promolink            = $cfg['promolink']            ?? $fallbackCfg['promolink']            ?? '/reg';
        $internal_reg_url     = $cfg['internal_reg_url']     ?? $fallbackCfg['internal_reg_url']     ?? '';
        $partner_override_url = $cfg['partner_override_url'] ?? $fallbackCfg['partner_override_url'] ?? '';
        $redirect_enabled     = (int)($cfg['redirect_enabled'] ?? $fallbackCfg['redirect_enabled'] ?? 0);
        $base_new_url         = $cfg['base_new_url']         ?? $fallbackCfg['base_new_url']         ?? '';
        $base_second_url      = $cfg['base_second_url']      ?? $fallbackCfg['base_second_url']      ?? '';

        // по умолчанию пусть будет assets/*
        $logo    = $cfg['logo']    ?? $fallbackCfg['logo']    ?? 'assets/logo.png';
        $favicon = $cfg['favicon'] ?? $fallbackCfg['favicon'] ?? 'assets/favicon.png';

        $out  = "<?php\n";
        $out .= "/**\n * AUTO-GENERATED by panel\n * DO NOT EDIT MANUALLY\n */\n\n";

        // базовые SEO переменные (нужны для '$inherit' в pages)
        $out .= '$title = ' . $this->q($title) . ";\n";
        $out .= '$description = ' . $this->q($description) . ";\n";
        $out .= '$keywords = ' . $this->q($keywords) . ";\n";
        $out .= '$h1 = ' . $this->q($h1) . ";\n\n";

        // pages
        $out .= "\$pages = [\n";
        foreach ($pages as $url => $page) {
            $url = (string)$url;
            if (!is_array($page)) $page = [];

            $out .= "  " . $this->q($url) . " => [\n";
            foreach ($page as $k => $v) {
                $k = (string)$k;

                if ($k === 'text_file') {
                    $file = (string)($v ?? '');
                    $file = ltrim($file, '/');
                    $file = basename($file ?: 'home.php');
                    $out .= "    " . $this->q($k) . " => __DIR__ . '/texts/" . $file . "',\n";
                    continue;
                }

                if (in_array($k, ['title', 'h1', 'description', 'keywords'], true) && $v === '$inherit') {
                    $out .= "    " . $this->q($k) . " => \${$k},\n";
                    continue;
                }

                $out .= "    " . $this->q($k) . " => " . $this->exportValue($v) . ",\n";
            }
            $out .= "  ],\n\n";
        }
        $out .= "];\n\n";

        // redirect/partner
        $out .= '$promolink = ' . $this->q($promolink) . ";\n";
        $out .= '$internal_reg_url = ' . $this->q($internal_reg_url) . ";\n";
        $out .= '$partner_override_url = ' . $this->q($partner_override_url) . ";\n";
        $out .= '$redirect_enabled = ' . $redirect_enabled . ";\n\n";
        $out .= '$base_new_url = ' . $this->q($base_new_url) . ";\n";
        $out .= '$base_second_url = ' . $this->q($base_second_url) . ";\n\n";

        // assets
        $out .= '$logo = ' . $this->q($logo) . ";\n";
        $out .= '$favicon = ' . $this->q($favicon) . ";\n\n";

        $out .= "?>";

        file_put_contents(rtrim($subDir, '/\\') . '/config.php', $out);
    }

    private function q($v): string
    {
        $s = (string)($v ?? '');
        $s = str_replace(['\\', "'"], ['\\\\', "\\'"], $s);
        return "'" . $s . "'";
    }

    private function exportValue($v): string
    {
        if ($v === null) return "''";
        if (is_bool($v)) return $v ? 'true' : 'false';
        if (is_int($v) || is_float($v)) return (string)$v;
        if (is_array($v)) return var_export($v, true);
        return $this->q($v);
    }
}

// Совместимость: если где-то вызывают new MultiSiteConfigWriter() без namespace
\class_alias(__NAMESPACE__ . '\\MultiSiteConfigWriter', 'MultiSiteConfigWriter');
